version: '3.8'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - mongo
      - redis
  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
  redis:
    image: redis:7
    ports:
      - "6380:6379" 