version: '3.8'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - mongo
      - redis
    volumes:
      - ./logs:/app/logs
  telegram_bot:
    build: .
    command: python telegram_polling.py
    env_file:
      - .env
    depends_on:
      - app
      - mongo
      - redis
    volumes:
      - ./logs:/app/logs
    restart: always
  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  redis:
    image: redis:7
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data

volumes:
  mongo_data:
  redis_data: 