version: '3.8'

networks:
  simple_network:
    driver: bridge

services:
  app_simple:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: universal_agent_simple
    ports:
      - "8080:8000"  # Используем другой порт чтобы не конфликтовать
    env_file:
      - .env
    volumes:
      - ./app:/app/app
      - ./logs:/app/logs
      - ./.env:/app/.env
    environment:
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=INFO
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      # Унифицированная конфигурация БД
      - MONGODB_URI=${MONGODB_URI:-mongodb://mongo:27017/}
      - MONGODB_DATABASE_NAME=${MONGODB_DATABASE_NAME:-universal_agent_platform}
      - MONGODB_TIMEOUT=${MONGODB_TIMEOUT:-30}
      - MONGODB_RETRY_ATTEMPTS=${MONGODB_RETRY_ATTEMPTS:-3}
      - MONGODB_RETRY_DELAY=${MONGODB_RETRY_DELAY:-5}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - HOST=0.0.0.0
      - PORT=8000
      - WORKERS=1
    command: python app/simple_main.py
    networks:
      - simple_network
    depends_on:
      - mongo
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Опциональная MongoDB (можно запускать без нее)
  mongo:
    image: mongo:6
    container_name: universal_agent_mongo_simple
    ports:
      - "27018:27017"  # Другой порт чтобы не конфликтовать
    volumes:
      - mongo_simple_data:/data/db
    restart: unless-stopped
    networks:
      - simple_network
    environment:
      - MONGO_INITDB_DATABASE=universal_agent_platform

volumes:
  mongo_simple_data: 