version: '3.8'

networks:  # Добавляем определение сети
  app_network:
    driver: bridge

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - MONGODB_DATABASE_NAME=universal_agent_platform
      - MONGO_URI=${MONGO_URI}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - API_URL=${API_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - LOG_LEVEL=${LOG_LEVEL}
    env_file:
      - .env
    depends_on:
      - mongo
      - redis
    volumes:
      - ./logs:/app/logs
      - ./:/app  # Для hot-reload, если нужно в разработке
    restart: unless-stopped
    networks:  # Подключаем сервис к сети
      - app_network
#  frontend:  # Временно комментируем сервис frontend
#    build:
#      context: ./frontend
#      dockerfile: Dockerfile
#    ports:
#      - "3000:3000"
#    env_file: # Если фронтенду нужны переменные окружения
#      - .env # или frontend/.env
#    restart: unless-stopped
#    depends_on:
#      - app
#    networks:  # Подключаем сервис к сети
#      - app_network
  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped
    networks:  # Подключаем сервис к сети
      - app_network
  redis:
    image: redis:7
    ports:
      - "6380:6379" # Маппинг 6380 хоста на 6379 контейнера
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:  # Подключаем сервис к сети
      - app_network

volumes:
  mongo_data:
  redis_data: 