version: '3.8'

services:
  # MongoDB для хранения агентов и сценариев
  mongodb:
    image: mongo:7.0
    container_name: uap_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: universal_agent_platform
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - uap_network

  # Universal Agent Platform API
  api:
    build: .
    container_name: uap_api
    restart: unless-stopped
    ports:
      - "8085:8085"
    volumes:
      - ./scenarios:/app/scenarios
      - ./logs:/app/logs:rw  # Права на запись для логов
    environment:
      # MongoDB подключение
      MONGODB_URL: mongodb://admin:password123@mongodb:27017/universal_agent_platform?authSource=admin
      MONGODB_DATABASE: universal_agent_platform
      
      # Telegram (опционально)
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN:-}
      
      # Logging
      LOG_LEVEL: INFO
      
      # API конфигурация
      HOST: 0.0.0.0
      PORT: 8085  # Синхронизируем с портом контейнера
      WORKERS: 1
    depends_on:
      mongodb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8085/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - uap_network

  # MongoDB Web UI (опционально)
  mongo-express:
    image: mongo-express:1.0
    container_name: uap_mongo_express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
      ME_CONFIG_MONGODB_URL: mongodb://admin:password123@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
    depends_on:
      - mongodb
    networks:
      - uap_network

volumes:
  mongodb_data:
    driver: local

networks:
  uap_network:
    driver: bridge 